[general]
indexer_name = "SCS AA Event Indexer"

[chains.minato]
rpc_url = "https://rpc.minato.soneium.org"
chain_id= 1946
block_time= 2
polling_blocks= 5 
active= true

[[chains.minato.contracts]]
name = "Sponsership_Paymaster"
address = "0xb28E459aB4a61e78b27768A37C92d902CA89F181"
events = [
    { signature = "0xb51885f42df18ff2d99621fa3752090f501b08a1b746ad11ecc8fa00e068b1db", name = "GasBalanceDeducted", params = ["address", "uint256", "uint256", "uint8"] },
    { signature = "0x94139248bcc22ab7c689ff34422119f69e04a937052f28621797cb5f69c45af7", name = "UserOperationSponsored", params = ["bytes32", "address"] },
    { signature = "0x3367befd2b2f39615cd79917c2153263c4af1d3945ec003e5d5bfc13a8d85833", name = "RefundProcessed", params = ["address", "uint256"] }
]

[[chains.minato.contracts]]
name = "Entrypoint_V0.7"
address = "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
events = [
    { signature = "0x49628fd1471006c1482da88028e9ce4dbb080b815c9b0344d39e5a8e6ec1419f", name = "UserOperationEvent", params = ["bytes32", "address", "address", "uint256", "bool", "uint256", "uint256"] }
]

[storage]
use_redis = true
redis_url = "redis://127.0.0.1:6379"
use_kafka = false
kafka_broker = "localhost:9092"
kafka_topics = ["aa_event_logs"]
